# ---- deps
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts

# ---- build
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NODE_ENV=production
RUN npm run build

# ---- run (distroless for security & size)
FROM gcr.io/distroless/nodejs20-debian12
WORKDIR /app
# Public assets
COPY --from=builder /app/public ./public
# Minimal server produced by Next standalone
COPY --from=builder /app/.next/standalone ./
# Next static files
COPY --from=builder /app/.next/static ./.next/static
# Runtime env
ENV NODE_ENV=production \
    HOST=0.0.0.0 \
    PORT=8080
USER nonroot:nonroot
EXPOSE 8080
# server.js is generated by Next in the standalone folder
CMD ["server.js"]